### ISSUE TITLE
TrustInSoft CI test

### ISSUE THREAD

**Issue by guillaumemillot** [paulkokos/ImageProcessingLibrary#3]
Hi @paulkokos ,

I noticed that you attempted to analyze this project with TrustInSoft CI.

As there's a little bit of configuration, I sent you this PR https://github.com/paulkokos/ImageProcessingLibrary/pull/2 to help you get started with TIS CI.

By merging this PR, you should get a result similar as this:
https://ci.trust-in-soft.com/projects/guillaumemillot/ImageProcessingLibrary/1

Next step would be for you to click on Explore to open the Analyzer and understand the cause of the Undefined Behavior.
Feel free to follow the tutorial in order to learn how to use the Analyzer interface:
https://docs.ci.trust-in-soft.com/tutorial/prepare-the-demo-project

I'd be happy to receive your feedback.

**Comment by paulkokos** [comment]
Thank you !
